name: Docker Image CI

on:
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: CHeckout COde
      uses: actions/checkout@v4
      
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false #true
        tags: |
          ghcr.io/${{ github.repository_owner }}/python3.11-trixie-slim-uv-chrome:latest
