name: Docker Image CI

on:
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --platform=linux/amd64,linux/arm64 --output "type=image,push=true" . --file Dockerfile --tag python3.11-trixie-slim-chrome-uv:$(date +%s)
